- Makefile
- run-scan.py
Kokkos build changes needed to build it elsewhere than on my laptop (e.g. machines at CERN or Cori).
> Update on Kokkos build and run-scan.py

- src/cuda/bin/main.cc
- src/cudatest/bin/main.cc
- src/fwtest/bin/main.cc
- src/kokkostest/bin/main.cc
The `--empty` should be empty always.
> Move transfer block under 'if not empty' in main

- src/cuda/bin/main.cc
- src/cudatest/bin/main.cc
- src/fwtest/bin/main.cc
- src/kokkostest/bin/main.cc
Non-formatted code slipped in...
> Code format

- src/cudatest/plugin-Test1/gpuAlgo1.cu
- src/cudatest/plugin-Test2/gpuAlgo2.cu
- src/kokkostest/plugin-Test1/kokkos/kokkosAlgo1.cc
- src/kokkostest/plugin-Test2/kokkos/kokkosAlgo2.cc
For the CPU versions to finish in reasonable time.
> Reduce test vector/matrix size to 1000

- Makefile
Share common flags between the host compiler (e.g. g++ ...) and the host compilation
of CUDA code (nvcc -Xcompiler ...).
Set the host compiler used by nvcc, both locally and when building cupla.
> Various small changes to build rules and environment

- src/kokkos/Geometry/phase1PixelTopology.h
- src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc
- src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClusterChargeCut.h
- src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClustering.h
A step towards porting the following kernels, done in a separate PR to ease concurrent development.
> [kokkos] Copy gpuClustering.h and gpuClusterChargeCut.h from cuda

- src/cuda/plugin-Validation/CountValidator.cc
- src/cudadev/plugin-Validation/CountValidator.cc
- src/cudauvm/plugin-Validation/CountValidator.cc
> Reduce verbosity of validation

- src/kokkos/DataFormats/BeamSpotPOD.h
- src/kokkos/Framework/EventSetup.h
- src/kokkos/Framework/ProductRegistry.h
- src/kokkos/KokkosDataFormats/BeamSpotKokkos.h
- src/kokkos/Makefile.deps
- src/kokkos/bin/main.cc
- src/kokkos/plugin-BeamSpotProducer/BeamSpotESProducer.cc
- src/kokkos/plugin-BeamSpotProducer/kokkos/BeamSpotToKokkos.cc
- src/kokkos/plugins.txt
Do I need to create a unit test as well?
> Add BeamSpotToKokkos

- src/cudauvm/CUDADataFormats/BeamSpotCUDA.cc
- src/cudauvm/CUDADataFormats/BeamSpotCUDA.h
- src/cudauvm/plugin-BeamSpotProducer/BeamSpotToCUDA.cc
> [cudauvm] Migrate BeamSpot transfer to managed memory

- src/kokkos/DataFormats/ZVertexSoA.h
- src/kokkos/KokkosDataFormats/ZVertexHeterogeneous.h
- src/kokkos/Makefile
- src/kokkos/Makefile.deps
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksByDensity.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksDBSCAN.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksIterative.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuFitVertices.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuSortByPt2.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuSplitVertices.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuVertexFinder.h
- src/kokkos/test/kokkos/VertexFinder_t.cc
Still have the runtime deadlock issue with serial. Will fix it and port other classes/functions not involved in the unit test shortly.
> Add Kokkos vertexing unit test

- src/cuda/test/TrackingRecHit2DCUDA_t.cu
- src/cuda/test/TrajectoryStateSOA_cpu_t.cc
- src/cuda/test/TrajectoryStateSOA_t.cu
- src/cuda/test/TrajectoryStateSOA_t.h
Somehow I missed earlier the tests in `CUDADataFormats/*/test`.
> [cuda] Add two more unit tests

- run-scan.py
- src/kokkos/KokkosCore/GPUVecArray.h
- src/kokkos/KokkosCore/HistoContainer.h
- src/kokkos/KokkosCore/eigenSoA.h
- src/kokkos/KokkosDataFormats/PixelTrackKokkos.h
- src/kokkos/KokkosDataFormats/TrajectoryStateSoA.h
- src/kokkos/plugin-PixelTriplets/CAConstants.h
- src/kokkos/plugin-PixelTriplets/CircleEq.h
- src/kokkos/plugin-PixelTriplets/GPUCACell.h
- src/kokkos/plugin-PixelTriplets/kokkos/BrokenLineFitOnGPU.cc
- src/kokkos/plugin-PixelTriplets/kokkos/BrokenLineFitOnGPU.h
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.h
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernelsImpl.h
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorOnGPU.cc
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorOnGPU.h
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletKokkos.cc
- src/kokkos/plugin-PixelTriplets/kokkos/FitResult.h
- src/kokkos/plugin-PixelTriplets/kokkos/HelixFitOnGPU.cc
- src/kokkos/plugin-PixelTriplets/kokkos/HelixFitOnGPU.h
- src/kokkos/plugin-PixelTriplets/kokkos/RiemannFitOnGPU.cc
- src/kokkos/plugin-PixelTriplets/kokkos/RiemannFitOnGPU.h
- src/kokkos/plugin-PixelTriplets/kokkos/gpuFishbone.h
- src/kokkos/plugin-PixelTriplets/kokkos/gpuPixelDoublets.h
- src/kokkos/plugin-PixelTriplets/kokkos/gpuPixelDoubletsAlgos.h
- src/kokkos/test/kokkos/TrajectoryStateSOA_t.cc
Data formats are migrated to Kokkos, none of the kernels are, but all the surrounding code should be.
> [kokkos] Add skeleton for CAHitNTupletKokkos

- src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc
- src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.h
- src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClusterChargeCut.h
- src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClustering.h
- src/kokkos/test/kokkos/clustering.cc
I think I have everything in place and I was able to run `kokkos --serial --maxEvents 10` and with `--cuda` without error.
> porting RawToCluster to Kokkos

- src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc
- src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.h
- src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClusterChargeCut.h
- src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClustering.h
- src/kokkos/test/kokkos/clustering.cc
- src/kokkos/test/kokkos/threadTeam.cc
> [kokkos] code format

- README.md
- src/kokkos/KokkosDataFormats/TrackingRecHit2DKokkos.h
- src/kokkos/bin/main.cc
- src/kokkos/plugin-SiPixelRecHits/kokkos/PixelRecHits.cc
~~This PR is work in progress to enable RecHit module.~~
This PR enables the RecHit module to be run.
> [kokkos] Enable RecHit module

- src/kokkos/KokkosDataFormats/TrackingRecHit2DKokkos.h
- src/kokkos/test/kokkos/TrackingRecHit2D_t.cc
experimental Kokkos version of RecHit module
> added a kokkos version of TrackingRecHit2DCuda test

- src/kokkos/Makefile
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorOnGPU.cc
- src/kokkos/plugin-PixelTriplets/kokkos/gpuPixelDoubletsAlgos.h
Continuation of #93, not ready yet.
> [kokkos] Working to get CAHitNtupletKokkos to run

- src/kokkos/Makefile
- src/kokkos/bin/main.cc
- src/kokkos/plugin-PixelTriplets/kokkos/BrokenLineFitOnGPU.cc
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorOnGPU.cc
- src/kokkos/plugin-PixelTriplets/kokkos/RiemannFitOnGPU.cc
- src/kokkos/plugin-Validation/kokkos/CountValidator.cc
Continuation of #94, CA works now with CUDA backend (not yet with serial), and passes the counting validation of tracks(!).
> [kokkos] CAHitNtupletKokkos runs on CUDA

- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc
`stride=1` is required for serial execution since team size must be 1.
> [kokkos] Use unit-stride loops for the serial execution

- src/cuda/CUDADataFormats/TrackingRecHit2DCUDA.cc
- src/cuda/CUDADataFormats/TrackingRecHit2DHeterogeneous.h
- src/cuda/bin/main.cc
- src/cuda/plugin-Validation/HistoValidator.cc
- src/cuda/plugin-Validation/SimpleAtomicHisto.h
- src/cuda/plugins.txt
- src/cuda/test/histo.cc
- src/kokkos/KokkosDataFormats/SiPixelDigisKokkos.h
- src/kokkos/KokkosDataFormats/TrackingRecHit2DKokkos.h
- src/kokkos/bin/main.cc
- src/kokkos/plugin-Validation/SimpleAtomicHisto.h
- src/kokkos/plugin-Validation/kokkos/HistoValidator.cc
- src/kokkos/plugins.txt
To help in understanding whether observed differences are numerical or indicating a bug.
> Add simple histogram-based validation

- plot-histograms.py
Add plotting script for the histograms of #104.
> Add plot-histograms.py

- src/cudadev/CUDACore/HistoContainer.h
- src/cudadev/CUDACore/prefixScan.h
- src/cudadev/plugin-PixelTriplets/CAHitNtupletGeneratorKernels.cc
- src/cudadev/plugin-PixelTriplets/CAHitNtupletGeneratorKernels.cu
- src/cudadev/plugin-PixelTriplets/CAHitNtupletGeneratorKernels.h
- src/cudadev/plugin-PixelTriplets/CAHitNtupletGeneratorKernelsAlloc.h
- src/cudadev/plugin-SiPixelClusterizer/SiPixelRawToClusterGPUKernel.cu
- src/cudadev/plugin-SiPixelRecHits/PixelRecHits.cu
- src/cudadev/test/HistoContainer_t.cu
- src/cudadev/test/OneToManyAssoc_t.h
- src/cudadev/test/prefixScan_t.cu
From https://github.com/cms-patatrack/cmssw/pull/447.
> [cudadev] Get rid of cub prefix-scan

- src/cuda/plugin-Validation/HistoValidator.cc
- src/kokkos/plugin-Validation/kokkos/HistoValidator.cc
These should be the relevant ones for physics.
> Fill histograms only from at least loose tracks

- README.md
- src/cudauvm/CUDADataFormats/SiPixelClustersCUDA.cc
- src/cudauvm/CUDADataFormats/SiPixelClustersCUDA.h
- src/cudauvm/CUDADataFormats/SiPixelDigiErrorsCUDA.cc
- src/cudauvm/CUDADataFormats/SiPixelDigiErrorsCUDA.h
- src/cudauvm/CUDADataFormats/SiPixelDigisCUDA.cc
- src/cudauvm/CUDADataFormats/SiPixelDigisCUDA.h
- src/cudauvm/plugin-SiPixelClusterizer/SiPixelRawToClusterCUDA.cc
- src/cudauvm/plugin-SiPixelClusterizer/SiPixelRawToClusterGPUKernel.cu
- src/cudauvm/plugin-SiPixelClusterizer/SiPixelRawToClusterGPUKernel.h
- src/cudauvm/plugin-SiPixelRawToDigi/SiPixelDigisSoAFromCUDA.cc
Part of https://github.com/cms-patatrack/pixeltrack-standalone/issues/43
> [cudauvm] Migrate clustering to use managed memory

- src/kokkos/plugin-PixelTriplets/GPUCACell.h
Apparently I merged #134 too soon, it actually results in a runtime failure when Kokkos runtime is built only with Serial backend
```
kokkos: .../pixeltrack-standalone/src/kokkos/plugin-PixelTriplets/kokkos/../GPUCACell.h:326: void GPUCACell::find_ntuplets(const Hits&, GPUCACell*, GPUCACell::CellTracksVector&, GPUCACell::HitContainer&, cms::kokkos::AtomicPairCounter&, GPUCACell::Quality*, GPUCACell::TmpTuple&, unsigned int, bool) const: Assertion `tmpNtuplet.size() <= 4' failed.
```
The culprit turned out to be the added calls to `Kokkos::atomic_compare_exchange()` whose effect somehow did not propagate correctly in this case. This PR introduces a workaround of direct assignment (which is what the `cudaCompat` approach uses for CPU execution as well).
> [kokkos] Workaround for assertion failure in serial-only build

- run-scan.py
Helps scan jobs against the failures https://github.com/cms-patatrack/cmssw/issues/306
> Add --tryAgain option to run-scan.py

- .gitignore
Start each entries with a `/` to match only in the main directory.
> Update .gitignore for test directory and binaries

- src/kokkos/KokkosCore/HistoContainer.h
- src/kokkos/KokkosCore/hintLightWeight.h
- src/kokkos/plugin-PixelTriplets/kokkos/BrokenLineFitOnGPU.cc
- src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc
- src/kokkos/plugin-PixelTriplets/kokkos/RiemannFitOnGPU.cc
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksByDensity.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksDBSCAN.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksIterative.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuSortByPt2.h
- src/kokkos/plugin-PixelVertexFinding/kokkos/gpuVertexFinder.cc
- src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc
- src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClusterChargeCut.h
- src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClustering.h
- src/kokkos/plugin-SiPixelRecHits/kokkos/PixelRecHits.cc
A stepping stone towards trying to call those operations concurrently.
> [kokkos] Use HintLightWeight in all Kokkos parallel operations

- Makefile
- src/cudatest/CUDACore/CachingDeviceAllocator.h
- src/cudatest/CUDACore/CachingHostAllocator.h
- src/cudatest/CUDACore/ScopedContext.cc
- src/cudatest/CUDACore/deviceAllocatorStatus.cc
- src/cudatest/CUDACore/deviceAllocatorStatus.h
- src/cudatest/CUDACore/getCachingDeviceAllocator.h
- src/cudatest/CUDACore/getCachingHostAllocator.h
- src/cudatest/Makefile
- src/cudatest/Makefile.deps
> [cudatest] Update cudatest from cuda, and remove CUB external

- README.md
- src/cudauvm/CUDADataFormats/HeterogeneousSoA.h
- src/cudauvm/CUDADataFormats/TrackingRecHit2DCUDA.cc
- src/cudauvm/CUDADataFormats/TrackingRecHit2DHeterogeneous.h
- src/cudauvm/plugin-PixelTriplets/CAHitNtupletGeneratorKernels.h
- src/cudauvm/plugin-Validation/HistoValidator.cc
> [cudauvm] Migrate rechit to use managed memory

- src/alpaka/AlpakaCore/AtomicPairCounter.h
- src/alpaka/test/alpaka/AtomicPairCounter_t.cc
Results as expected for the 3 backends.
> [alpaka] Add AtomicPairCounter to alpaka/AlpakaCore and alpaka/test

- README.md
- src/cudauvm/CUDADataFormats/HeterogeneousSoA.h
- src/cudauvm/CUDADataFormats/PixelTrackHeterogeneous.h
- src/cudauvm/CUDADataFormats/ZVertexHeterogeneous.h
- src/cudauvm/plugin-PixelTrackFitting/PixelTrackSoAFromCUDA.cc
- src/cudauvm/plugin-PixelTriplets/CAHitNtupletGeneratorKernels.cu
- src/cudauvm/plugin-PixelTriplets/CAHitNtupletGeneratorKernels.h
- src/cudauvm/plugin-PixelTriplets/CAHitNtupletGeneratorOnGPU.cc
- src/cudauvm/plugin-PixelVertexFinding/PixelVertexSoAFromCUDA.cc
- src/cudauvm/plugin-PixelVertexFinding/gpuVertexFinderImpl.h
Part of https://github.com/cms-patatrack/pixeltrack-standalone/issues/43
> [cudauvm] Migrate tracking and vertexing to unified memory

- Makefile
This PR updated the version of Eigen to include the changes originally developed by the Patatrack team, please some fixes added by Eric.
> Update the version of Eigen to include the Patatrack changes

- Makefile
This should improve performance, but measuring the impact is still to be done (after merging the PR, I have again a bit of backlog there).
> Add option to build Kokkos-Threads with hwloc

- Makefile
Reuse `$(CUDA_LIBDIR)` instead of `$(CUDA_BASE)/lib64`.
> Reuse CUDA_LIBDIR

- src/cuda/CUDACore/ESProduct.h
- src/cuda/CUDACore/ScopedSetDevice.h
- src/cudacompat/CUDACore/ESProduct.h
- src/cudacompat/CUDACore/ScopedSetDevice.h
- src/cudadev/CUDACore/ESProduct.h
- src/cudadev/CUDACore/ScopedSetDevice.h
- src/cudauvm/CUDACore/ESProduct.h
- src/cudauvm/CUDACore/ScopedSetDevice.h
- src/hip/CUDACore/ESProduct.h
- src/hip/CUDACore/ScopedSetDevice.h
From https://github.com/cms-sw/cmssw/pull/34948 (and https://github.com/cms-sw/cmssw/pull/34968)
I did not try to compile the `hip` version.
FYI @fwyzard
> Fix uploading the EventSetup conditions to multiple CUDA devices

- Makefile
> [alpaka] Update Alpaka to 0.8.0-rc1

- src/alpakatest/AlpakaCore/CachingAllocator.h
Propagating #316 to `alpakatest`
> [alpakatest] Fix CachingAllocator for pinned host memory in presence of multiple devices

- analyze-results.py
- run-scan.py
Record the CPU thread efficiency added in https://github.com/cms-patatrack/pixeltrack-standalone/pull/324, and include also a possibility for the "`ps` sampling method" that I used in #321 (mostly because I had the code there already).
> Add two ways to record CPU utilization to run-scan.py

- src/kokkos/bin/main.cc
- src/kokkostest/bin/main.cc
Slipped through in https://github.com/cms-patatrack/pixeltrack-standalone/pull/246 ...
> [kokkos] Fix setting of tbb::global_control

- src/stdpar/CUDACore/HistoContainer.h
- src/stdpar/CUDACore/portableAtomicOp.h
- src/stdpar/plugin-PixelTriplets/CAHitNtupletGeneratorKernels.cu
- src/stdpar/plugin-PixelVertexFinding/gpuClusterTracksByDensity.h
- src/stdpar/plugin-PixelVertexFinding/gpuClusterTracksDBSCAN.h
- src/stdpar/plugin-PixelVertexFinding/gpuClusterTracksIterative.h
- src/stdpar/plugin-PixelVertexFinding/gpuSortByPt2.h
- src/stdpar/plugin-PixelVertexFinding/gpuSplitVertices.h
- src/stdpar/plugin-PixelVertexFinding/gpuVertexFinder.h
- src/stdpar/plugin-PixelVertexFinding/gpuVertexFinderImpl.h
- src/stdpar/plugin-SiPixelClusterizer/SiPixelRawToClusterGPUKernel.cu
- src/stdpar/plugin-SiPixelClusterizer/gpuClustering.h
- src/stdpar/test/OneHistoContainer_t.cu
- src/stdpar/test/OneToManyAssoc_t.h
- src/stdpar/test/VertexFinder_t.h
- src/stdpar/test/gpuClustering_t.h
This PR finish the porting of `HistoContainer`to stdpar. Also update all the kernels and tests depending on it to stdpar.
> Stdpar histo container

- run-many.py
- run-scan.py
Various small bugs that came up while running measurements for CHEP23.
> Small fixes to run-scan.py and run-many.py
