cms-patatrack/pixeltrack-standalone

Makefile, src/cuda/Makefile, src/cudatest/Makefile, src/fwtest/Makefile, src/kokkostest/Makefile
Fix Kokkos building recipe with
- `external_kokkos` to point to the right dependence
- avoid running CMake configure every time
- pass `$(CXX)` to `nvcc_wrapper`
Also clean up direct dependence from the .so files to source files, there is already dependence via the object files (which is more correct anyway).
=> Makefile fixes and cleanup

src/cuda/Makefile, src/cudatest/Makefile
The `$(strip ..)` function strips all extra whitespace, and allows `$(1)_CUOBJ` to be assigned from multiple variables. Strictly speaking this change is not needed now for `cudatest` or `cuda` (but e.g. `kokkostest` will need it), but I think it is better have it in these as well because they will likely be used as a base Makefiles for subsequent programs.
=> Improve check .cu file existence check in Makefiles

Makefile, README.md, src/cuda/Framework/ESPluginFactory.h, src/cuda/Framework/PluginFactory.h, src/cuda/Makefile, src/cudatest/Framework/ESPluginFactory.h, src/cudatest/Framework/PluginFactory.h, src/cudatest/Makefile, src/fwtest/Framework/ESPluginFactory.h, src/fwtest/Framework/PluginFactory.h, src/fwtest/Makefile, src/kokkostest/Framework/ESPluginFactory.h, src/kokkostest/Makefile
If/when we use namespaces for different backends, the macros `DEFINE_FWK_MODULE` and `DEFINE_FWK_EVENTSETUP_MODULE` better work with namespaces (solution copied from CMSSW, original was not).
I also add test targets (`test` for all tests, `test_{cpu,cuda}` for the CPU and CUDA platforms, and `test_<program>_{cpu,cuda}` for the elements of the full program x platform matrix).
=> Make module macros compatible with namespaces, and add test targets to Makefile

src/alpaka/Framework/ESPluginFactory.h, src/cuda/Framework/ESPluginFactory.h, src/cudatest/Framework/ESPluginFactory.h, src/fwtest/Framework/ESPluginFactory.h, src/kokkostest/Framework/ESPluginFactory.h
I left `src/alpaka/plugin-SiPixelClusterizer/clustering_alpaka.cc` intentionally out to not cause conflicts with developments by @felicepantaleo and @waredjeb. Let's deal with the formatting when the `alpaka` code becomes more integrated.
=> Code format

.gitignore, Makefile, README.md
Updates to the build rules:
- fix Boost detection on Debian/Ubuntu systems (from #22)
- make the minimum required version of Boost more explicit
- update external version of Boost to 1.73.0
Updates to the runtime environment:
- add CUPLA_LIBDIR to the environment
- save and reuse the original PATH and LD_LIBRARY_PATH variables
=> Various small changes to build rules and runtime environment

src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClustering.h
I updated the `gpuClustering::countModules()` function from cuda to kokkos as a first test for me.
=> porting countModules to Kokkos

Makefile, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc
Small follow-up to https://github.com/cms-patatrack/pixeltrack-standalone/pull/33
- Replace the remaining call to `Kokkos::fence()` with `KokkosExecSpace().fence()`
- Change Kokkos target architecture to Volta (covers running on both Volta and Turing)
=> Small updates to Kokkos

run-scan.py, src/cudauvm/CondFormats/PixelCPEFast.cc, src/cudauvm/CondFormats/PixelCPEFast.h, src/cudauvm/CondFormats/SiPixelFedCablingMapGPUWrapper.cc, src/cudauvm/CondFormats/SiPixelFedCablingMapGPUWrapper.h, src/cudauvm/CondFormats/SiPixelGainCalibrationForHLTGPU.cc, src/cudauvm/CondFormats/SiPixelGainCalibrationForHLTGPU.h, src/cudauvm/bin/main.cc, src/cudauvm/plugin-SiPixelClusterizer/SiPixelRawToClusterCUDA.cc, src/cudauvm/plugin-SiPixelRecHits/SiPixelRecHitCUDA.cc
Part of #43. Kind of equivalent to https://github.com/cms-patatrack/cmssw/pull/157.
By default `cudaMemAdvise()` and `cudaMemPrefetchAsync()` are enabled, but there are compile-time switches to disable them.
=> [cudauvm] Move conditions to use managed memory

Makefile, README.md
The CUDA target architecture defaults to `70` (Volta). Currently only `75` (Turing) is listed as an alternative. More are easy to add, these just suffice my immediate needs.
When updating local code run
```
make clean
rm -fR external/kokkos
```
=> [kokkos] Update Kokkos to 3.1.01, require target CUDA architecture to be specified explicitly

Makefile, src/kokkos/KokkosCore/kokkosConfig.h, src/kokkos/KokkosCore/kokkosConfigCommon.h, src/kokkos/KokkosCore/kokkoshost/kokkosConfigCommon.cc, src/kokkos/KokkosDataFormats/BeamSpotKokkos.h, src/kokkos/KokkosDataFormats/SiPixelDigiErrorsKokkos.h, src/kokkos/bin/main.cc, src/kokkos/plugin-BeamSpotProducer/kokkos/BeamSpotToKokkos.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelFedCablingMapESProducer.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelGainCalibrationForHLTESProducer.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc, src/kokkos/test/kokkos/AtomicPairCounter_t.cc, src/kokkos/test/kokkos/clustering.cc, src/kokkostest/KokkosCore/kokkosConfig.h, src/kokkostest/KokkosCore/kokkosConfigCommon.h, src/kokkostest/KokkosCore/kokkoshost/kokkosConfigCommon.cc, src/kokkostest/bin/main.cc, src/kokkostest/plugin-Test1/kokkos/kokkosAlgo1.cc, src/kokkostest/plugin-Test2/kokkos/kokkosAlgo2.cc, src/kokkostest/test/kokkos/world.cc
New attempt of https://github.com/cms-patatrack/pixeltrack-standalone/pull/33. Now also all execution space specific unit tests initialize only that unit test, i.e. all `X.serial` binaries can be run without a GPU.
=> [kokkos] Initialize and use only the backend(s) given at the command line

src/kokkos/DataFormats/approx_atan2.h, src/kokkos/KokkosDataFormats/SiPixelClustersKokkos.h, src/kokkos/KokkosDataFormats/SiPixelDigisKokkos.h, src/kokkos/KokkosDataFormats/TrackingRecHit2DKokkos.h, src/kokkos/KokkosDataFormats/TrackingRecHit2DSOAView.h, src/kokkos/plugin-SiPixelRecHits/kokkos/PixelRecHits.cc, src/kokkos/plugin-SiPixelRecHits/kokkos/PixelRecHits.h, src/kokkos/plugin-SiPixelRecHits/kokkos/SiPixelRecHitKokkos.cc, src/kokkos/plugin-SiPixelRecHits/kokkos/gpuPixelRecHits.h, src/kokkos/test/kokkos/threadTeam.cc
This PR migrates two of the RecHit kernels to Kokkos. The third one needs `HistoContainer`, and will be done after #62. They compile, but I can't test running them (yet).
This PR also adds a simple unit test to play with the Kokkos' thread teams.
=> [kokkos] Migrate two RecHit kernels to Kokkos

src/kokkos/Makefile.deps, src/kokkos/bin/main.cc, src/kokkos/plugin-PixelTriplets/kokkos/PixelTrackSoAFromKokkos.cc, src/kokkos/plugin-PixelVertexFinding/kokkos/PixelVertexProducerKokkos.cc, src/kokkos/plugin-PixelVertexFinding/kokkos/PixelVertexSoAFromKokkos.cc, src/kokkos/plugin-Validation/kokkos/CountValidator.cc, src/kokkos/plugins.txt
Also update `plugins.txt` and add placeholders to `main.cc`.
This PR should complete porting all the non-kernel ("boilerplate") module code to Kokkos.
=> [kokkos] Port track and vertex device-to-host transfer modules, and the validation module

src/kokkostest/KokkosCore/Product.h, src/kokkostest/KokkosCore/ProductBase.h, src/kokkostest/KokkosCore/ScopedContext.h, src/kokkostest/KokkosCore/kokkoshost/ProductBase.cc, src/kokkostest/Makefile.deps, src/kokkostest/plugin-Test2/kokkos/TestProducer2.cc
This PR is a follow-up to https://github.com/cms-patatrack/pixeltrack-standalone/pull/58 and adds support for external worker.
=> [kokkostest] Add ScopedContextAcquire and test external worker

src/kokkos/KokkosDataFormats/SiPixelClustersKokkos.h, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToCluster.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.h, src/kokkos/plugin-Validation/kokkos/CountValidator.cc
This PR makes several updates to `SiPixelRawToCluster` module
* Enable the event products
* Various fixes
* Remove unnecessary fences
With this PR the module runs for both serial and CUDA backends, and passes the (simple counting) validation for both.
=> [kokkos] Finalize SiPixelRawToCluster module

src/kokkos/bin/main.cc, src/kokkos/plugin-Validation/kokkos/CountValidator.cc
Note that the serial backend current fails with
```
Kokkos::abort: Requested Team Size is too large!Aborted
```
and CUDA backend does not pass validation (possibly serial doesn't either).
=> [kokkos] Enable vertexing module

src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc, src/kokkos/plugin-SiPixelRecHits/kokkos/PixelCPEFastESProducer.cc
This PR makes the number of pixel vertices to become non-zero. The number of vertices still doesn't pass the validation though (for neither serial or CUDA backend).
=> [kokkos] Fix bugs

src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc
Brings validation closer, now 1 event passes (on CUDA but not on serial), but of the first 100 events 49 fail on CUDA backend and 77 on serial backend.
=> [kokkos] Fix kernel launch parameters

src/cuda/plugin-Validation/CountValidator.cc, src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc, src/kokkos/plugin-Validation/kokkos/CountValidator.cc
In addition, print out average differences in track and vertex counts.
With this update the `kokkos` program passes `--validation` for both CUDA and serial backends.
=> [kokkos] Fix more kernel launch parameters

Makefile, src/cudatest/plugin-Test1/gpuAlgo1.cu, src/cudatest/plugin-Test2/gpuAlgo2.cu
Hard code CUDA version 10.2, since CUDA 11.0 fails to run and CUDA 11.1 fails to build.
Silence CUDA warnings about deprecated architectures.
Remove duplicate use of `esa_on_defaulted_function_ignored`.
Fix a bug in the matrixMulVector test.
=> various CUDA-related improvements

Makefile, README.md, src/alpaka/Makefile, src/alpakatest/Makefile, src/cuda/Makefile, src/cudadev/Makefile, src/cudatest/Makefile, src/cudauvm/Makefile, src/fwtest/Makefile, src/kokkos/Makefile, src/kokkostest/Makefile, src/sycltest/Makefile
New attempt to be more flexible with the build targets, based on the discussion in https://github.com/cms-patatrack/pixeltrack-standalone/pull/112.
=> Use CUDA_BASE and SYCL_BASE to choose targets to include in all, create hardware-specific test targets

src/cuda/plugin-SiPixelRecHits/gpuPixelRecHits.h
Required in order to compile with `-DGPU_DEBUG` .
=> Fix debug-only CUDA code

src/kokkos/KokkosCore/HistoContainer.h
This is a more performance workaround for Kokkos not providing team-wide prefix scan.
=> [kokkos] Replace Nx parallel_scan() with one parallel_scan()+2x parallel_for() in HistoContainer finalize()

README.md, src/cudauvm/CUDADataFormats/BeamSpotCUDA.cc, src/cudauvm/CUDADataFormats/BeamSpotCUDA.h, src/cudauvm/CondFormats/PixelCPEFast.cc, src/cudauvm/CondFormats/SiPixelFedCablingMapGPUWrapper.cc, src/cudauvm/CondFormats/SiPixelGainCalibrationForHLTGPU.cc, src/cudauvm/bin/main.cc
While (slowly) working on the raw-to-cluster part, it occurred to me that it `cudaMemAdvise()` is used with a cached allocation, it better be un-done before returning the memory to the cache.
At first I got weird errors
```
terminate called after throwing an instance of 'std::runtime_error'
what():  
.../pixeltrack-standalone/src/cudauvm/CUDADataFormats/BeamSpotCUDA.cc, line 22:
cudaCheck(cudaMemAdvise(data_d_.get(), sizeof(Data), cudaMemAdviseUnsetReadMostly, device_));
cudaErrorDeviceUninitialized: invalid device context
```
(usually with `./cudauvm --validation`). It turned out that in these cases the destructor was run in a different thread than the constructor (i.e. the process was started with one thread, and TBB created a second thread because of`enqueue()` call), and the other …
=> [cudauvm] Need to unset memory advise in BeamSpotCUDA destructor

README.md, src/cudauvm/CUDADataFormats/BeamSpotCUDA.cc, src/cudauvm/CUDADataFormats/BeamSpotCUDA.h, src/cudauvm/bin/main.cc, src/cudauvm/plugin-BeamSpotProducer/BeamSpotToCUDA.cc
My earlier approach for measuring the performance impact of gradually enabling managed memory in the modules would have required active work through them to measure the throughput properly for each PR, and would not allow proper way to reproduce the results later. I'm changing the approach to have per-module macros allow disabling the use of managed memory (even if that makes the `#ifdef` logic more messy).
=> [cudauvm] Add a macro to allow disabling the use of managed memory in BeamSpotToCUDA module

Makefile
Also filter out `-Werror=missing-braces` from CUDA flags used with Alpaka to circumvent a compilation error. Resolves #126.
After this PR `make distclean` (or `rm -fR external/alpaka`)  is needed in existing developer areas.
FYI @fwyzard @ghugo83
=> [alpaka] Update Alpaka to 0.5.0

Makefile
Requires either `make distclean` or `rm -fR external/kokkos`
=> [kokkos] Update Kokkos to 3.2

Makefile, src/kokkostest/KokkosCore/ProductBase.h, src/kokkostest/KokkosCore/kokkosConfig.h, src/kokkostest/plugin-Test1/kokkos/kokkosAlgo1.cc, src/kokkostest/plugin-Test2/kokkos/kokkosAlgo2.cc
In general the execution space `fence()` needs to be called at the synchronization points (which are treated differently with CUDA by using events and callback functions).
The `HintLightWeight` should disable the constant cache optimization of Kokkos, which prohibits concurrent calls to `parallel_X`. I created a helper function reduce the necessary boilerplace on client code.
I also improved a bit the `make format` implementation because I was confused by "No such file or directory" error I was getting (in the end it was caused by something else, but the new structure helped to pinpoint it).
=> [kokkostest] Polishing the "device framework" prototype

src/alpakatest/AlpakaCore/alpakaConfig.h, src/alpakatest/plugin-Test1/alpaka/alpakaAlgo1.cc, src/alpakatest/plugin-Test2/alpaka/alpakaAlgo2.cc
Add simple vectorProd, matrixMul, matrixVectorMul tests to alpakatest.
Compiles and runs smoothy with serial, tbb and GPU cases.
Calling the 3 Producers, on 1000 events, with size N=1000, I get similar throughput comparing Alpaka(CUDA) with native CUDA style kernels (GPU Quadro M1200):
- cudatest: ~17.8 events/s
- alpakatest --cuda: ~16.6 events/s
Hence potentially a small overhead with Alpaka(CUDA), which I presume is expected (consistent with the 6% overhead found in the literature).
NB 1: I was getting wrong results with vectorAdd in the serial and tbb cases.  
Indeed, there was no loop on the elements. Hence, only one value every 32 was calculated, in the serial and tbb cases. 
vectorAdd is now fixed in this PR (all results have been cross-checked). Was this expected?
NB 2: Following …
=> [alpakatest] Add cudatest tests to alpakatest tests

run-scan.py
Usage:
```
./run-scan.py --numThreads 4 --eventsPerStream 1000 --repeat 4 --overwrite --warmup ./cuda 
20-12-06 10:19:55 Warming up
20-12-06 10:20:01 Processed 4000 events in 5.067138e+00 seconds, throughput 789.4 events/s.
20-12-06 10:20:01 Number of streams 4 threads 4 events 4000
20-12-06 10:20:06 Processed 4000 events in 4.927730e+00 seconds, throughput 811.733 events/s.
20-12-06 10:20:12 Processed 4000 events in 4.954347e+00 seconds, throughput 807.372 events/s.
20-12-06 10:20:17 Processed 4000 events in 4.949005e+00 seconds, throughput 808.243 events/s.
20-12-06 10:20:23 Processed 4000 events in 4.941497e+00 seconds, throughput 809.471 events/s.
20-12-06 10:20:23 Number of streams 4 threads 4, average throughput 809.204750
```
The first measurement is run but its results are …
=> Add warmup option to run the command once before starting the profiling

Makefile
This new one is the one used in CMSSW_11_2_0_pre8_Patatrack (and earlier), the one used before is the commit used as the base of patches applied by CMS.
Resolves #147.
Update needs either `make distclean` or `rm -fR external/eigen`.
=> Use the correct version of Eigen

Makefile
Requires `make distclean` or `make clean; rm -fR external/kokkos`.
=> [kokkos] Update Kokkos to 3.3

Makefile
Currently can come up if both CUDA and ROCm toolchains are detected.
=> Remove duplicate targets in case they could be enabled by many toolchains

src/alpaka/Makefile, src/alpakatest/AlpakaCore/alpakaConfig.h, src/alpakatest/Makefile, src/alpakatest/plugin-Test1/alpaka/TestProducer.cc, src/alpakatest/plugin-Test1/alpaka/alpakaAlgo1.cc, src/alpakatest/plugin-Test1/alpaka/alpakaAlgo1.h, src/alpakatest/plugin-Test2/alpaka/TestProducer2.cc, src/alpakatest/plugin-Test2/alpaka/TestProducer3.cc, src/alpakatest/plugin-Test2/alpaka/alpakaAlgo2.cc, src/alpakatest/plugin-Test2/alpaka/alpakaAlgo2.h
Event data can now be stored, and accessed with getToken directly from Acc memory, no need to transfer data to CPU.
NB: At a later stage: There should likely be implementations in AlpakaCore of ScopedContext, similar to what is done in KokkosCore; skipped for now.
=> [alpakatest] Add return types to alpakatest algos

src/kokkos/bin/main.cc, src/kokkostest/bin/main.cc
The option turned out to be rather confusing in the end (given that the pthread backend turned out to require all Kokkos calls to originate from one specific thread). This PR removes the `--numberOfInnerThreads` option and uses the `--numberOfThreads` option instead.
=> [kokkos] Remove -- numberOfInnerThreads command line argument

README.md, src/cuda/CUDACore/getCachingDeviceAllocator.h, src/cudadev/CUDACore/getCachingDeviceAllocator.h, src/cudatest/CUDACore/getCachingDeviceAllocator.h, src/cudauvm/CUDACore/getCachingDeviceAllocator.h
For all four CUDA programs with separate macros. Intended only to test the impact of disabling the caching allocator (that is significant).
=> [cuda] Add compile macros to disable caching allocator

src/kokkos/KokkosCore/HistoContainer.h, src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterFillHist.h, src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksByDensity.h, src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksDBSCAN.h, src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksIterative.h, src/kokkos/plugin-PixelVertexFinding/kokkos/gpuVertexFinder.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClustering.h, src/kokkos/test/kokkos/OneHistoContainer_t.cc, src/kokkos/test/kokkos/VertexFinder_t.cc
I tried to fuse multiple kernels into one since `finalize()` is now a device function but got a sequence of different errors. Will do it next week.
=> [kokkos] Rewrite Hist::finalize() with Teamscan

src/alpaka/AlpakaCore/HistoContainer.h, src/alpaka/AlpakaCore/alpakaWorkDivHelper.h, src/alpaka/AlpakaCore/prefixScan.h, src/alpaka/test/alpaka/AtomicPairCounter_t.cc, src/alpaka/test/alpaka/HistoContainer_t.cc, src/alpaka/test/alpaka/OneHistoContainer_t.cc, src/alpaka/test/alpaka/OneToManyAssoc_t.cc, src/alpaka/test/alpaka/clustering_alpaka.cc, src/alpaka/test/alpaka/prefixScan_t.cc, src/alpakatest/AlpakaCore/alpakaWorkDivHelper.h, src/alpakatest/plugin-Test1/alpaka/alpakaAlgo1.cc, src/alpakatest/plugin-Test2/alpaka/alpakaAlgo2.cc
Run smoothly and results are consistent with 'pure CUDA' versions.
=> Add AlpakaCore/HistoContainer.h + HistoContainer_t, OneHistoContainer_t and OneToManyAssoc_t tests

Makefile
Implies `make distclean` or more surgical `rm -fR external/kokkos`.
=> Update Kokkos to 3.3.01

Makefile
This solves two potential problems:
- running on a system where `wget` is not available, but `curl` is;
- running behind a SOCKS5 proxy, that `curl` supports but `wget` does not.
=> Use consistently curl instead of wget

Makefile, README.md, src/cuda/CUDACore/allocate_device.cc, src/cuda/CUDACore/allocate_device.h, src/cuda/CUDACore/allocate_host.cc, src/cuda/CUDACore/device_unique_ptr.h, src/cuda/CUDACore/getCachingDeviceAllocator.h, src/cudadev/CUDACore/allocate_device.cc, src/cudadev/CUDACore/allocate_device.h, src/cudadev/CUDACore/allocate_host.cc, src/cudadev/CUDACore/device_unique_ptr.h, src/cudadev/CUDACore/getCachingDeviceAllocator.h, src/cudatest/CUDACore/allocate_device.cc, src/cudatest/CUDACore/allocate_device.h, src/cudatest/CUDACore/allocate_host.cc, src/cudatest/CUDACore/device_unique_ptr.h, src/cudatest/CUDACore/getCachingDeviceAllocator.h
If the caching allocator is disabled and CUDA version is 11.2 or greater is detected, device allocations and deallocations will use the stream-ordered CUDA functions `cudaMallocAsync` and `cudaFreeAsync`.
Their use can be disabled explicitly at compile time setting also the `CUDA_DISABLE_ASYNC_ALLOCATOR` preprocessor symbol.
=> CUDA: use the stream-ordered memory allocations if the caching allocator is disabled

src/alpaka/AlpakaCore/HistoContainer.h, src/alpaka/AlpakaCore/alpakaWorkDivHelper.h, src/alpaka/AlpakaCore/prefixScan.h, src/alpaka/CUDACore/CMSUnrollLoop.h, src/alpaka/test/alpaka/AtomicPairCounter_t.cc, src/alpaka/test/alpaka/OneHistoContainer_t.cc, src/alpaka/test/alpaka/OneToManyAssoc_t.cc, src/alpaka/test/alpaka/prefixScan_t.cc, src/alpakatest/AlpakaCore/alpakaWorkDivHelper.h, src/alpakatest/plugin-Test1/alpaka/alpakaAlgo1.cc, src/alpakatest/plugin-Test2/alpaka/alpakaAlgo2.cc
This contains a number of fixes in the prefixScan AlpakaCore version and its test.
The diff should appear clean after https://github.com/cms-patatrack/pixeltrack-standalone/pull/165 is merged. In the meantime, can also simply just click at the diff of src/alpaka/AlpakaCore/prefixScan.h and  src/alpaka/test/alpaka/prefixScan_t.cc.
**Minor corrections:**
- Remove unsupported use of `#pragma unroll`.
- Cannot use `__restrict__` in `warpPrefixScan `and `blockPrefixScan`, as they are called with `blockPrefixScan(acc, psum, psum, numBlocks, ws)`, in MultiBlock second step, hence with `ci = co = psum`.
- Remove unused variables.
- Handle element-dependency in `testPrefixScan` for the serial and TBB cases.
- Take into account the newly added back-ends in the workDiv computation.
- Make workloads …
=> Adjustments in AlpakaCore/prefixScan and its test + Add helper functions to handle workdiv

Makefile, Makefile.cupla, src/alpaka/AlpakaCore/AtomicPairCounter.h, src/alpaka/AlpakaCore/HistoContainer.h, src/alpaka/AlpakaCore/alpakaConfig.h, src/alpaka/AlpakaCore/alpakaWorkDivHelper.h, src/alpaka/AlpakaCore/prefixScan.h, src/alpaka/plugin-SiPixelClusterizer/gpuClusterChargeCut.h, src/alpaka/plugin-SiPixelClusterizer/gpuClustering.h, src/alpaka/test/alpaka/AtomicPairCounter_t.cc, src/alpaka/test/alpaka/HistoContainer_t.cc, src/alpaka/test/alpaka/OneHistoContainer_t.cc, src/alpaka/test/alpaka/OneToManyAssoc_t.cc, src/alpaka/test/alpaka/clustering_t.cc, src/alpaka/test/alpaka/prefixScan_t.cc, src/alpakatest/AlpakaCore/alpakaConfig.h, src/alpakatest/AlpakaCore/alpakaWorkDivHelper.h, src/alpakatest/plugin-Test1/alpaka/alpakaAlgo1.cc, src/alpakatest/plugin-Test2/alpaka/alpakaAlgo2.cc, src/alpakatest/test/alpaka/world.cc
Update the `alpakatest` and `alpaka` sources following the changes in the Alpaka namespaces and symbol names:
```sed
s#alpaka::acc::#alpaka::#g
s#alpaka::atomic::atomicOp#alpaka::atomicOp#g
s#alpaka::atomic::op::Add#alpaka::AtomicAdd#g
s#alpaka::atomic::op::And#alpaka::AtomicAnd#g
s#alpaka::atomic::op::Cas#alpaka::AtomicCas#g
s#alpaka::atomic::op::Dec#alpaka::AtomicDec#g
s#alpaka::atomic::op::Exch#alpaka::AtomicExch#g
s#alpaka::atomic::op::Inc#alpaka::AtomicInc#g
s#alpaka::atomic::op::Max#alpaka::AtomicMax#g
s#alpaka::atomic::op::Min#alpaka::AtomicMin#g
s#alpaka::atomic::op::Or#alpaka::AtomicOr#g
s#alpaka::atomic::op::Sub#alpaka::AtomicSub#g
s#alpaka::atomic::op::Xor#alpaka::AtomicXor#g
s#alpaka::block::shared::dyn::getMem#alpaka::getDynSharedMem#g …
```
=> Update Alpaka to 0.6.0, and Cupla to the latest dev snapshot

Makefile
Boost download link is broken. 
Boost version was upgraded from 1.73.0 to 1.76.0
=> fix broken Boost download

src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc
The `kokkos --cuda` failed in asserts with CUDA 11.2 o V100 about parallel_scan being used without power-of-2 number of threads per team. This was the only use of `TeamPolicy` wit `Kokkos::AUTO()` number of threads that calls team-wide `parallel_scan`.
The `kokkos --cuda`  runs now with both CUDA 11.2 and 11.3 on V100.
=> Use explicit number of threads per team for remaining team-wide parallel_scan

Makefile, src/cuda/CUDACore/cudaCheck.h, src/cuda/Makefile.deps
When `cudaCheck()` detects a CUDA error, in addition to the file and line number of the call, print a full stack trace.
For example:
```
/home/cern/pixeltrack-standalone/src/cuda/CUDACore/CachingDeviceAllocator.h, line 559:
cudaCheck(error = cudaGetLastError());
cudaErrorIllegalAddress: an illegal memory access was encountered
Current stack trace:
0# cms::cuda::abortOnCudaError(char const*, int, char const*, char const*, char const*, char const*) at /home/cern/pixeltrack-standalone/src/cuda/CUDACore/cudaCheck.h:35
1# 0x00007F47541E637B at /home/cern/pixeltrack-standalone/src/cuda/CUDACore/cudaCheck.h:61
2# cms::cuda::free_device(int, void*, CUstream_st*) at /home/cern/pixeltrack-standalone/src/cuda/CUDACore/allocate_device.cc:40
3# …
```
=> Print a stack trace on CUDA errors

src/cudadev/CUDACore/getCachingDeviceAllocator.h, src/cudatest/CUDACore/getCachingDeviceAllocator.h
Fix the CUDA version detection for the `cudatest` and `cudadev` programs.
=> [cudatest,cudadev] Fix the fallback to the stream ordered CUDA memory operations

Makefile
Keep the generated PTX in the final binaries.
This should have two advantages:
- allow running on newer GPUs that were not explicitly targeted thanks to the JIT compilation
- allow to extract and inspect the generated PTX
=> [cuda] Keep PTX in the final binaries

src/cuda/bin/main.cc, src/cudadev/bin/main.cc, src/cudatest/bin/main.cc
Configure the default CUDA memory pool to cache memory allocations, following a similar behaviour to the cub caching allocator.
See *Using the NVIDIA CUDA Stream-Ordered Memory Allocator* in the NVIDIA developer blog ([part 1](https://developer.nvidia.com/blog/using-the-nvidia-cuda-stream-ordered-memory-allocator-part-1/), [part 2](https://developer.nvidia.com/blog/using-the-nvidia-cuda-stream-ordered-memory-allocator-part-2/)) for more information, and the various options for tuning the CUDA memory pools.
Achieves a small speed up when using the memory pool, but still much slower than the caching allocator:
```
Found 1 devices
Processing 8000 events, of which 8 concurrently, with 8 threads.
Processed 8000 events in 9.022492e+00 seconds, throughput 886.673 events/s.
Processed 8000 events …
```
=> Tune the CUDA memory pool used by the stream ordered memory operations

src/cuda/CUDACore/ESProduct.h, src/cudacompat/CUDACore/ESProduct.h, src/cudadev/CUDACore/ESProduct.h, src/cudauvm/CUDACore/ESProduct.h, src/hip/CUDACore/ESProduct.h
When multiple CUDA streams are trying to initialise the same EventSetup object, the first one to do
so starts the asynchronous operations, and the others are supposed to wait for it to finish.
However, code for recording the CUDA event was missing, so the other streams would find the default-
constructed event, which is always "valid".
Adding the missing call to record the event fixes the problem.
=> Fix uploading EventSetup conditions from multiple CUDA streams

src/cudadev/CUDACore/cudaCompat.h, src/cudadev/plugin-PixelTriplets/GPUCACell.h, src/cudadev/plugin-PixelVertexFinding/gpuFitVertices.h, src/cudadev/plugin-PixelVertexFinding/gpuSortByPt2.h, src/cudadev/plugin-SiPixelClusterizer/gpuClustering.h
Use block-wise atomic operations.
Add missing memory fences to avoid crashes on Ampere (and potentially other) GPUs.
=> [cudadev] Minimal updates from CMSSW_12_0_0_pre5

Makefile
CUDA_BASE is used by the alpaka sub-make to decide whether to build CUDA support or not. However, the top-level Makefile did not export it, so the detection would work only if the variable was set explicitly in the environment or on the command line.
Export CUDA_BASE so the the Alpaka sub-make can find properly it.
Update alpaka to version 0.6.1.
=> Updates to alpaka

src/hip/CUDACore/cudaCheck.h
The definition of BOOST_INLINE in boost and AMD's definition of `__noinline__ `collide to create an erroneous `__attribute_` clause.  Fix it by defining BOOST_INLINE.
=> Fix compile issue with BOOST_NOINLINE and HIP

src/cuda/test/radixSort_t.cu, src/cudacompat/test/radixSort_t.cu, src/cudadev/test/radixSort_t.cu, src/cudauvm/test/radixSort_t.cu, src/hip/test/radixSort_t.cu
Fix the compilation errors in test/radixSort_t.cu:
- take into account the actual size of the type being sorted, instead of always assuming a 64-bit type;
- use an union instead of a cast to keep the compiler happy about the aliasing rules.
=> [all] Fix radix sort test

src/hip/CUDACore/radixSort.h
Fix the radixSort_t test.
Remove the launch bounds, which seem to cause the kernel to fail to run (and no error is raised)
Add  `__threadfence` after the update of the ibs variable, which controls the enclosing while loop.  Without this threadfence, the loop appears to keep running, and the preceding assert will trigger (`c[bin] >= 0`).
This PR replaces #195
=> Workarounds for the HIP port

Makefile
Fixes compilation problems with CUDA 11.3 and later.
See [libeigen/eigen!586](https://gitlab.com/libeigen/eigen/-/merge_requests/586) for more details.
=> [all] Update Eigen and extend CUDA support

src/cuda/Makefile, src/cudacompat/Makefile, src/cudadev/Makefile, src/cudatest/Makefile, src/cudauvm/Makefile, src/hip/Makefile, src/hiptest/Makefile
Fixed missing dependency files inclusion. The compilation was successfully tested on `cuda*`, but `hip` and `hiptest` do not compile in the current version, so this PR introduces an untested (although low risk) port for them.
Also added optional targets to generate the preprocessor output, useful for debugging macros.
=> Makefile fix

src/cudadev/CUDACore/GenericCachingAllocator.h, src/cudadev/CUDACore/allocate_device.cc, src/cudadev/CUDACore/allocate_host.cc, src/cudadev/CUDACore/deviceAllocatorStatus.cc, src/cudadev/CUDACore/deviceAllocatorStatus.h, src/cudadev/CUDACore/getCachingDeviceAllocator.h, src/cudadev/CUDACore/getCachingHostAllocator.h
This PR abstracts the commonalities between `CachingDeviceAllocator` and `CachingHostAllocator` into a class template, with two traits classes providing the device/host-specific functionality. This abstraction should help with
- maintenance and evolution of the caching allocator (less copy-pasted code)
* I have some ideas for reducing the number of CUDA events as part of https://github.com/cms-sw/cmssw/issues/30266
- porting the caching allocator to other APIs (device interaction is abstracted into the traits class)
I'd expect no performance difference, but that is still to be measured. After the review here I'm planning to propagate the changes to CMSSW.
=> [cudadev] Generalize caching allocator

src/hip/CUDACore/ESProduct.h
Code introduced in 9f46b5695a7055577078f63702992a40b15056d8 added a call to ScopedSetDevice that should be in the cms::hip namespace in the hip port.
=> Fix namespace in hip port

src/kokkos/CUDACore/EventCache.cc, src/kokkos/CUDACore/EventCache.h, src/kokkos/CUDACore/ScopedSetDevice.h, src/kokkos/CUDACore/SharedEventPtr.h, src/kokkos/CUDACore/SharedStreamPtr.h, src/kokkos/CUDACore/StreamCache.cc, src/kokkos/CUDACore/StreamCache.h, src/kokkos/CUDACore/cudaCheck.h, src/kokkos/CUDACore/currentDevice.h, src/kokkos/CUDACore/deviceCount.h, src/kokkos/CUDACore/eventWorkHasCompleted.h, src/kokkos/Framework/ReusableObjectHolder.h, src/kokkos/KokkosCore/ContextState.h, src/kokkos/KokkosCore/ExecSpaceCache.h, src/kokkos/KokkosCore/Product.h, src/kokkos/KokkosCore/ProductBase.h, src/kokkos/KokkosCore/ScopedContext.h, src/kokkos/KokkosCore/kokkoshost/ProductBase.cc, src/kokkos/KokkosCore/kokkoshost/kokkosConfigCommon.cc, src/kokkos/Makefile.deps, src/kokkos/plugin-BeamSpotProducer/kokkos/BeamSpotToKokkos.cc, src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletKokkos.cc, src/kokkos/plugin-PixelTriplets/kokkos/PixelTrackSoAFromKokkos.cc, src/kokkos/plugin-PixelVertexFinding/kokkos/PixelVertexProducerKokkos.cc, src/kokkos/plugin-PixelVertexFinding/kokkos/PixelVertexSoAFromKokkos.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToCluster.cc, src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc, src/kokkos/plugin-SiPixelRecHits/kokkos/SiPixelRecHitKokkos.cc, src/kokkos/plugin-Validation/kokkos/CountValidator.cc, src/kokkos/plugin-Validation/kokkos/HistoValidator.cc
Introduces caching of the Execution Space objects in addition to what is in `kokkostest` (in principle should be "backported" there). The Execution Space objects are "heavy", and should be treated similarly to CUDA streams. With the caching the performance drop on a "one concurrent event" case is about 1-2 %.
With the Kokkos 3.4.1 only the CUDA backend works (as in runs and passes `--validation`) with multiple concurrent events and CPU threads. With Kokkos `develop` branch (i.e. their next version) also Serial backend works technically, but the performance is poor because of a "global lock". The performance of concurrent calls to Serial backend is expected to be improved in future versions of Kokkos. The performance of Kokkos-CUDA version is also bad, but because of continuous memory …
=> [kokkos] Use "device framework" in Kokkos version

src/kokkos/KokkosCore/AtomicPairCounter.h
When running Kokkos with the HIP backend there is an assertion failure in `assert (c.m < n);` in the first loop ("update") in `src/kokos/test/kokkos/AtomicPairCounter_t.cc`.
The failure seems to be because the `counters` member is not initialized in the default constructor.   This was pretty clear from printing out values of `c.m` before the counter update.
The straight HIP port calls `hipMemset` to initialize the object to zero after allocation, so the problem does not occur there.
=> Fix AtomicPairCounter test for Kokkos/HIP

src/alpaka/DataFormats/SiPixelDigisSoA.cc, src/alpaka/Framework/ReusableObjectHolder.h, src/alpaka/Framework/WaitingTaskList.cc, src/alpaka/plugin-Validation/SimpleAtomicHisto.h
Follow-up to https://github.com/cms-patatrack/pixeltrack-standalone/pull/242#discussion_r730900326
=> [alpaka] Replace ALPAKA_ASSERT_OFFLOAD with assert in places that should not depend on Alpaka

src/alpaka/AlpakaCore/EventCache.h, src/alpaka/AlpakaCore/ScopedSetDevice.h, src/alpaka/AlpakaCore/StreamCache.h, src/alpaka/AlpakaCore/alpaka/alpakaDevAcc.cc, src/alpaka/AlpakaCore/alpakaDevAcc.h, src/alpaka/AlpakaCore/alpakaMemoryHelper.h, src/alpaka/plugin-BeamSpotProducer/alpaka/BeamSpotToAlpaka.cc, src/alpaka/plugin-PixelTriplets/alpaka/CAHitNtupletAlpaka.cc, src/alpaka/plugin-PixelTriplets/alpaka/PixelTrackSoAFromAlpaka.cc, src/alpaka/plugin-PixelVertexFinding/alpaka/PixelVertexProducerAlpaka.cc, src/alpaka/plugin-PixelVertexFinding/alpaka/PixelVertexSoAFromAlpaka.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelFedCablingMapESProducer.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelGainCalibrationForHLTESProducer.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelRawToCluster.cc, src/alpaka/plugin-SiPixelRecHits/alpaka/PixelCPEFastESProducer.cc, src/alpaka/plugin-SiPixelRecHits/alpaka/SiPixelRecHitAlpaka.cc, src/alpaka/plugin-Validation/alpaka/HistoValidator.cc
Support building `alpaka` without CUDA support.
Support running without CUDA devices when `alpaka` is built with CUDA support.
=> [alpaka] Make the CUDA dependency optional

src/alpaka/AlpakaCore/radixSort.h, src/alpaka/plugin-PixelVertexFinding/alpaka/gpuClusterTracksByDensity.h, src/alpaka/plugin-PixelVertexFinding/alpaka/gpuClusterTracksDBSCAN.h, src/alpaka/plugin-PixelVertexFinding/alpaka/gpuClusterTracksIterative.h, src/alpaka/plugin-PixelVertexFinding/alpaka/gpuFitVertices.h, src/alpaka/plugin-PixelVertexFinding/alpaka/gpuSplitVertices.h, src/alpaka/plugin-SiPixelClusterizer/alpaka/gpuClusterChargeCut.h, src/alpaka/plugin-SiPixelClusterizer/alpaka/gpuClustering.h, src/alpaka/plugin-SiPixelRecHits/alpaka/gpuPixelRecHits.h
For atomics that operate on shared memory objects, operations don't need to be atomic among different blocks. 
The hierarchy for these atomics operations has been modified to avoid contention when running on CPU parallel backends.
Speedup of about 10% was observed with tbb backend.
=> [alpaka] modify hierarchy for atomics

src/alpaka/plugin-PixelTriplets/alpaka/GPUCACell.h, src/cuda/plugin-PixelTriplets/GPUCACell.h, src/cudauvm/plugin-PixelTriplets/GPUCACell.h, src/kokkos/plugin-PixelTriplets/GPUCACell.h
I experienced invalid memory errors on A100 (with CUDA 11.2 and 11.3, more frequently with 11.3 than with 11.2) with `cuda` but not with `cudadev`. Comparing the codes I found that `cudadev` had these `__threadfence()` calls that `cuda` did not. Those were added in CMSSW in https://github.com/cms-sw/cmssw/pull/34386. `cudauvm` has the same issue too.
The `alpaka` and `kokkos` programs ran fine now on A100, but I'd guess the threadfence calls would need to be propagated to those too.
=> [cuda,alpaka,kokkos] Add threadfence calls to be able to run 'cuda' on A100

Makefile, README.md
Bump the Boost requirement to version 1.73.0 for boost::atomic_ref .
Mark the include paths for Boost and the other externals as system ones,
to avoid generating compiler warnings for the external code.
=> Update the Boost dependency and the use of external header files

src/alpaka/AlpakaCore/HistoContainer.h
Remove the `__restrict__` attribute on the GPU pointers used on the CPU.
=> [alpaka] Remove unnecessary `__restrict__` attributes

src/alpaka/AlpakaCore/prefixScan.h, src/alpaka/plugin-PixelTriplets/alpaka/CAHitNtupletGeneratorKernelsImpl.h, src/alpaka/plugin-PixelTriplets/alpaka/gpuPixelDoublets.h, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelRawToClusterGPUKernel.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/gpuClustering.h
Fix warnings about unused variables:
- remove completely unused variables;
- mark variables that are used in `ALPAKA_ASSERT_OFFLOAD` as `[[maybe_unused]]`.
=> [alpaka] Fix unused variables warnings

src/hip/plugin-PixelTriplets/GPUCACell.h
These mirror the threadfence calls added in #263
These were necessary to reduce invalid memory errors in the CUDA version.
=> Add threadfence calls in HIP version

Makefile
`CC` is not used by oiur Makefiles, but is inherited by the configuration and compilation of the externals.
Defining it in a single place together with `CXX` makes it easier to remember and to change them consistently.
=> Add a variable to set the C compiler

analyze-results.py, run-many.py, run-scan.py
* Minimal fixes to `run-many.py` to get it to run
* Add `--bkgThreads` option to `run-scan.py` to be able to spawn multiple background processes instead of one with many threads
* Add option to specify number of events (per program) in `run-many.py`, either as the number of events directly, or as the number of events per stream
* When running many instances of same program with same threading settings, specifying the (same) number of events for them leads to smaller "edge effects" than running the programs for "about the same time"
* Add optional monitoring of CPU clock to `run-scan.py` and `run-many.py`
* Allow arbitrary program arguments to be passed in `run-many.py`
* Add a (work in progress) script to print out numbers from the result JSON files.
=> Updates to scanning scripts

src/alpaka/AlpakaCore/alpakaConfigAcc.h, src/alpaka/AlpakaCore/alpakaConfigCommon.h, src/alpaka/AlpakaCore/alpakaMemoryHelper.h, src/alpaka/AlpakaDataFormats/BeamSpotAlpaka.h, src/alpaka/AlpakaDataFormats/SiPixelClustersAlpaka.h, src/alpaka/AlpakaDataFormats/SiPixelDigiErrorsAlpaka.h, src/alpaka/AlpakaDataFormats/SiPixelDigisAlpaka.h, src/alpaka/AlpakaDataFormats/TrackingRecHit2DAlpaka.h, src/alpaka/CondFormats/PixelCPEFast.h, src/alpaka/CondFormats/SiPixelFedCablingMapGPUWrapper.h, src/alpaka/CondFormats/SiPixelGainCalibrationForHLTGPU.h, src/alpaka/plugin-PixelTriplets/alpaka/BrokenLineFitOnGPU.cc, src/alpaka/plugin-PixelTriplets/alpaka/CAHitNtupletGeneratorKernels.h, src/alpaka/plugin-PixelTriplets/alpaka/CAHitNtupletGeneratorOnGPU.cc, src/alpaka/plugin-PixelTriplets/alpaka/CAHitNtupletGeneratorOnGPU.h, src/alpaka/plugin-PixelTriplets/alpaka/RiemannFitOnGPU.cc, src/alpaka/plugin-PixelVertexFinding/alpaka/gpuVertexFinder.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelRawToClusterGPUKernel.cc
Change the interface and behaviour of `allocDeviceBuf` to take as argument a `Queue&` instead of a `Device const&`, and allocate stream-ordered (or queue-ordered) memory.
The memory is scheduled for freeing when the buffer is destroyed, but is actually freed only when the queue reaches that point on the device side.
=> [alpaka] Use stream-ordered device memory buffers

src/alpaka/plugin-SiPixelRecHits/alpaka/PixelRecHits.cc
The `alpaka::wait(queue)` is required to ensure all async operations complete before the host buffer inside the `hits_d` temporary variable goes out of scope and destroyed. It should be possible to remove it once the host buffers are stream-ordered.
=> [alpaka] Add back a required synchronisation

src/alpaka/plugin-Validation/alpaka/CountValidator.cc
Reverts cms-patatrack/pixeltrack-standalone#238 following discussion in https://github.com/cms-patatrack/pixeltrack-standalone/pull/238#issuecomment-1013139694 showing that the random issue has disappeared since (likely because of all the updates in between).
=> Revert "[alpaka] Increase vertex count tolerance to 2 to avoid spurious test failures"

src/alpaka/AlpakaCore/prefixScan.h
`alpaka::ignore_unused` has been removed in the alpaka `develop` branch.
=> [alpaka] cleanup unused parameters

src/alpaka/AlpakaCore/AtomicPairCounter.h, src/alpaka/AlpakaDataFormats/BeamSpotAlpaka.h, src/alpaka/AlpakaDataFormats/SiPixelClustersAlpaka.h, src/alpaka/AlpakaDataFormats/SiPixelDigiErrorsAlpaka.h, src/alpaka/AlpakaDataFormats/SiPixelDigisAlpaka.h, src/alpaka/AlpakaDataFormats/TrackingRecHit2DAlpaka.h, src/alpaka/CondFormats/PixelCPEFast.h, src/alpaka/CondFormats/SiPixelFedCablingMapGPUWrapper.h, src/alpaka/CondFormats/SiPixelGainCalibrationForHLTGPU.h, src/alpaka/plugin-BeamSpotProducer/alpaka/BeamSpotToAlpaka.cc, src/alpaka/plugin-PixelTriplets/alpaka/BrokenLineFitOnGPU.cc, src/alpaka/plugin-PixelTriplets/alpaka/CAHitNtupletGeneratorKernels.cc, src/alpaka/plugin-PixelTriplets/alpaka/CAHitNtupletGeneratorKernels.h, src/alpaka/plugin-PixelTriplets/alpaka/CAHitNtupletGeneratorOnGPU.cc, src/alpaka/plugin-PixelTriplets/alpaka/RiemannFitOnGPU.cc, src/alpaka/plugin-PixelVertexFinding/alpaka/PixelVertexProducerAlpaka.cc, src/alpaka/plugin-PixelVertexFinding/alpaka/gpuVertexFinder.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelRawToClusterGPUKernel.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelRawToClusterGPUKernel.h, src/alpaka/plugin-Validation/alpaka/CountValidator.cc, src/alpaka/plugin-Validation/alpaka/HistoValidator.cc, src/alpaka/test/alpaka/AtomicPairCounter_t.cc, src/alpaka/test/alpaka/HistoContainer_t.cc, src/alpaka/test/alpaka/OneHistoContainer_t.cc, src/alpaka/test/alpaka/OneToManyAssoc_t.cc, src/alpaka/test/alpaka/clustering_t.cc, src/alpaka/test/alpaka/prefixScan_t.cc
0-dimensional (scalar) buffers now implement the dereference `*` and member access `->` operators.
1-dimensional buffers now implement the array subscript `[]` operators.
all buffers implement the `.data()` method to access the underlying pointer.
=> [alpaka] Simplify the interface for host and device buffers

src/alpaka/AlpakaDataFormats/alpaka/TrackingRecHit2DAlpaka.h
Replaces the 14 memory buffers used in the `alpaka` version with 2 larger memory buffers, as is done in the `cuda` version.
=> [alpaka] Restructure TrackingRecHit2DAlpaka with SoA's like the cuda version

README.md, src/alpaka/AlpakaCore/AllocatorConfig.h, src/alpaka/AlpakaCore/AllocatorPolicy.h, src/alpaka/AlpakaCore/CachedBufAlloc.h, src/alpaka/AlpakaCore/CachingAllocator.h, src/alpaka/AlpakaCore/alpakaMemory.h, src/alpaka/AlpakaCore/getDeviceCachingAllocator.h, src/alpaka/AlpakaCore/getHostCachingAllocator.h, src/alpaka/AlpakaDataFormats/alpaka/SiPixelDigiErrorsAlpaka.h, src/alpaka/AlpakaDataFormats/alpaka/SiPixelDigisAlpaka.h, src/alpaka/AlpakaDataFormats/alpaka/TrackingRecHit2DAlpaka.h, src/alpaka/CondFormats/alpaka/PixelCPEFast.h, src/alpaka/CondFormats/alpaka/SiPixelFedCablingMapGPUWrapper.h, src/alpaka/CondFormats/alpaka/SiPixelGainCalibrationForHLTGPU.h, src/alpaka/plugin-BeamSpotProducer/alpaka/BeamSpotToAlpaka.cc, src/alpaka/plugin-PixelTrackFitting/alpaka/PixelTrackSoAFromAlpaka.cc, src/alpaka/plugin-PixelVertexFinding/alpaka/PixelVertexSoAFromAlpaka.cc, src/alpaka/plugin-Validation/alpaka/HistoValidator.cc, src/alpaka/test/alpaka/AtomicPairCounter_t.cc, src/alpaka/test/alpaka/HistoContainer_t.cc, src/alpaka/test/alpaka/OneHistoContainer_t.cc, src/alpaka/test/alpaka/OneToManyAssoc_t.cc, src/alpaka/test/alpaka/clustering_t.cc
Implement a caching allocator based on the `cuda`/`cudadev` one for device memory and pinned host memory.
The performance profile of the `alpaka --cuda` program now follows the one of the `cuda` program, while still having a ~5% performance degradation (shown in the plot after merging #307 and #308):
=> [alpaka] Host and device memory caching allocator

src/alpaka/AlpakaCore/alpakaConfig.h
Revert a change mistakenly introduced in the last reorganisation of the Alpaka configuration.
=> [alpaka] Fix the use of non-blocking queues with TBB

src/alpaka/plugin-SiPixelRecHits/alpaka/PixelRecHits.cc
Synchronise the queues and wait for the host-device copies to complete only when using the TBB async backend, without the caching allocator.
=> [alpaka] Sync TB host copies only when needed

src/hip/CUDACore/deviceAllocatorStatus.h, src/hip/CondFormats/SiPixelFedCablingMapGPUWrapper.cc, src/hip/DataFormats/SiPixelDigisSoA.h, src/serial/DataFormats/SiPixelDigisSoA.h
[hip] - cstring for std::memcpy and cstddef for size_t
[serial] - cstddef for size_t
=> Add missing include files

src/alpaka/AlpakaCore/CachingAllocator.h
I noticed that `alpaka` (and `alpakatest`)  was crashing with
```
Processing 1000 events, of which 2 concurrently, with 2 threads.
terminate called after throwing an instance of 'std::runtime_error'
what():  .../pixeltrack-standalone/external/alpaka/include/alpaka/event/EventUniformCudaHipRt.hpp(157) 'cudaEventRecord( event.m_spEventImpl->m_UniformCudaHipEvent, queue.m_spQueueImpl->m_UniformCudaHipQueue)' returned error  : 'cudaErrorInvalidResourceHandle': 'invalid resource handle'!
```
when run on 2 GPUs. I managed to trace the problem into the pinned host memory allocations in CachingAllocator, when a pinned host memory block was previously used on device A, and is then used on device B.
The current code does
```cpp
// Take previous device from *the argument block*
auto const& …
```
=> [alpaka] Fix CachingAllocator for pinned host memory in presence of multiple devices

Makefile
The libstdc++ library used by the devtools on RHEL 7 / CentOS 7 requires a workaround because some STL containers do not support the allocator traits, even when using more recent compilers.
=> Add workaround for building oneTBB with CentOS 7 devtools compilers

Makefile
Building `hip` and `hiptest` on CentOS 7 with GCC 9.2 requires Boost 1.78 or later, in order to pick the fix for https://github.com/boostorg/config/issues/392 .
Tested with various versions of ROCm from 4.0.0 to 5.0.1.
=> Update Boost to version 1.78.0

src/hip/CUDACore/cudaCheck.h
This reverts commit 4ad85d8c368658629244122ef48a5eca1b63555c.
The workaround is no longer necessary after the move to Boost 1.78.0.
=> Revert "Fix compile issue with BOOST_NOINLINE and HIP"

src/alpaka/test/alpaka/AtomicPairCounter_t.cc, src/alpaka/test/alpaka/HistoContainer_t.cc, src/alpaka/test/alpaka/OneHistoContainer_t.cc, src/alpaka/test/alpaka/OneToManyAssoc_t.cc, src/alpaka/test/alpaka/clustering_t.cc, src/alpaka/test/alpaka/prefixScan_t.cc
Fixes assertion failure in DeviceCachingAllocator. With this PR all the unit tests in `alpaka` run successfully for Serial, TBB, and CUDA backends.
=> [alpaka] Initialize devices in many alpaka unit test

run-many.py, run-scan.py
Follow up to https://github.com/cms-patatrack/pixeltrack-standalone/pull/325
=> Propagate per-thread CPU efficiency through run-many.py

Makefile, src/kokkos/KokkosCore/kokkoshost/kokkosConfigCommon.cc
The Kokkos update to 3.5 turned out to decrease the throughput by 2-3x. Disabling "Desul atomics" (that Kokkos was changed to use by default in 3.5) appears to cure the issue, but this is only a temporary workaround, because the "old atomics implementation" is going to be phased out. The issue is being followed up with Kokkos developers in https://github.com/kokkos/kokkos/issues/4780.
In addition, this PR adds support for using Kokkos' profiling tools via the `KOKKOS_PROFILE_LIBRARY` environment variable. (functionality that we were missing because of heavily customized initialization of Kokkos).,
=> [kokkos] Disable Desul atomics temporarily to improve performance

Makefile
Update the version of alpaka to the HEAD of the develop branch as of 2022.03.15, corresponding to the commit eff3dcee30 .
Relevant changes:
- add a grid-wise memory fence.
=> [alpaka] Update the develop branch to 2022.03.15 / eff3dcee30

src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClusterChargeCut.h
The Kokkos serial backend is slower than the plain serial code  - see #297 for more details.
One cause is addressed here, where the Kokkos backend loops over the entire array (size 1024) rather than the number of clusters (about 10).
This loop also sets ok and newclusId to zero.  Those get set later and these assignments can be removed.
=> [kokkos] serial backend performance fix

Makefile, src/alpaka/Makefile, src/alpakatest/Makefile
Replace `ALPAKA_CUFLAGS` with `CUDA_CUFLAGS`, since dropping some of the compiler options is no longer needed.
Drop the rules for building .cu files, which are not used with Alpaka.
=> [alpaka] Remove unneeded variables and rules from the Makefiles

Makefile
Update the version of alpaka to the HEAD of the develop branch as of 2022.03.18, corresponding to the commit 343e6de3d62 .
Relevant changes:
- fix the host-only compilation for the HIP backend
=> [alpaka] Update the develop branch to 2022.03.18 / 343e6de3d62

Makefile
The consistency is needed for `SPLIT_TARGETS_template` to function properly. Otherwise programs depending on ROCm end up in `TARGETS` even when `ROCM_BASE` is undefined, leading to `make all` to fail in such case.
Found and tested while testing #342.
=> Rename TARGETS_HIP to TARGETS_ROCM in Makefile

Makefile, src/alpaka/AlpakaCore/HostOnlyTask.h, src/alpaka/AlpakaCore/prefixScan.h, src/alpakatest/AlpakaCore/HostOnlyTask.h
Update the version of alpaka to the HEAD of the develop branch as of 2022.03.26, corresponding to the commit 3093418d887 .
Relevant changes:
- rename the namespace `alpaka::traits` to `alpaka::trait`.
=> [alpaka] Update the develop branch to 2022.03.26 / 3093418d887

src/alpaka/AlpakaCore/alpakaWorkDiv.h, src/alpaka/test/alpaka/prefixScan_t.cc, src/alpakatest/AlpakaCore/alpakaWorkDiv.h, src/alpakatest/plugin-Test1/alpaka/alpakaAlgo1.cc, src/alpakatest/plugin-Test2/alpaka/alpakaAlgo2.cc
`alpaka`:
- add  a missing `#include` directive;
- remove unused variable.
`alpakatest`:
- add  a missing `#include` directive;
- silence warnings about unused variables.
=> [alpaka] Minor fixes

src/sycltest/SYCLCore/ScopedContext.cc
Also aggregate messages from all the caught asynchronous exceptions in `sycl_exception_handler` (I believe this was the intention).
Tested adding an intentional error that the exception thrown via `sycl_exception_handler()` gets propagated to the mock framework.
=> [sycltest] Propagate asynchronous exception to WaitingTaskWithArenaHolder

Makefile
Looks like `CLANG_RESOURCE_DIR` and `CLANG_RUNTIME_DIR` are only used internally, so we don't need to pass them explicitly.
The use of `$(ROCM_BASE)/hip/include` and `$(ROCM_BASE)/hsa/include` is not necessary, because they are symlinked to (or from) `$(ROCM_BASE)/include`, and their use is deprecated in ROCm 5.2.
=> [hip] Simplify HIP compilation flags

Makefile
Update the version of alpaka to the HEAD of the develop branch as of 2022.08.15,
corresponding to the commit 540397c4297 .
Major changes:
- use CUDART_VERSION instead of BOOST_LANG_CUDA;
- implement const buffers with the ViewConst adaptor;
- ensure that tasks submitted to async CPU queues are completed even
after the queue is destroyed;
- use a callback thread instead of launching a new thread for each
CUDA asynchronous host function;
- update and refactor HIP/CUDA atomic implementations.
Other changes:
- add missing template parameters;
- add braces around aggregate initializer;
- added demangled type names;
- introduce alpaka::math::constants.
- update and clean up Update SysInfo.hpp.
Update the supported host compilers:
- add support for gcc 12;
- drop support for clang 5.
Various bug …
=> [alpaka] Update the develop branch to 2022.08.15 / 540397c4297

Makefile, src/alpaka/AlpakaCore/CachingAllocator.h, src/alpaka/AlpakaCore/alpakaMemory.h, src/alpaka/CondFormats/alpaka/PixelCPEFast.h, src/alpaka/CondFormats/alpaka/SiPixelFedCablingMapGPUWrapper.h, src/alpaka/CondFormats/alpaka/SiPixelGainCalibrationForHLTGPU.h, src/alpaka/plugin-BeamSpotProducer/alpaka/BeamSpotToAlpaka.cc, src/alpaka/plugin-PixelTrackFitting/alpaka/PixelTrackSoAFromAlpaka.cc, src/alpaka/plugin-PixelVertexFinding/alpaka/PixelVertexSoAFromAlpaka.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelRawToClusterGPUKernel.cc, src/alpaka/plugin-SiPixelClusterizer/alpaka/SiPixelRawToClusterGPUKernel.h, src/alpakatest/AlpakaCore/CachingAllocator.h, src/alpakatest/AlpakaCore/alpakaMemory.h
Add non-cached, pinned, host buffers, and use them instead of pageable memory to recover a performance close to that of native CUDA.
=> [alpaka] add non-cached pinned host buffers

src/stdpar/CUDACore/portableAtomicOp.h, src/stdpar/plugin-SiPixelRecHits/PixelRecHits.cu, src/stdpar/plugin-SiPixelRecHits/SiPixelRecHitCUDA.cc, src/stdpar/plugin-SiPixelRecHits/gpuPixelRecHits.h
Port `plugin-SiPixelRecHits` to `std::par`. There is only one Kernel to port, `getHits` uses a threading model of one thread block per detector module.  Current `std::par` implementation does a `std::for_each` call, with one iteration per module so each module will be processed by a single thread.
=> [stdpar] Port SiPixelRecHits

Makefile, src/openmp/DataFormats/SOARotation.h, src/openmp/Makefile, src/openmp/plugin-SiPixelClusterizer/gpuClusterChargeCut.h, src/openmp/plugin-SiPixelClusterizer/gpuClustering.h
Add openmp offload to three routines in SiPixelClusterizer.
Update the build to work with the NVHPC compiler.
The code runs and passes validation when compiled with LLVM.  
The code fails with assertion failures when compiled with NVHPC (22.7)
=> [openmp] Add offload to SiPixelClusterizer and update build for NVHPC compiler

src/openmp/Geometry/phase1PixelTopology.h
Replace 'result_of' with 'invoke_result'.
The warning
```
/home/mdewing/hep/patatrack/pixeltrack-standalone/src/openmp/Geometry/phase1PixelTopology.h:55:35: warning: 'result_of<unsigned char (*(unsigned long))(unsigned int)>' is deprecated: use 'std::invoke_result' instead [-Wdeprecated-declarations]
-> std::array<typename std::result_of<Function(std::size_t)>::type, sizeof...(Indices)> {
^
/home/mdewing/hep/patatrack/pixeltrack-standalone/src/openmp/Geometry/phase1PixelTopology.h:99:57: note: in instantiation of function template specialization 'phase1PixelTopology::map_to_array<116, unsigned char (*)(unsigned int)>' requested here
constexpr std::array<uint8_t, layerIndexSize> layer = map_to_array<layerIndexSize>(findLayerFromCompact);
^ …
```
=> [openmp] Replace deprecated C++ library function

src/stdpar/CUDACore/portableAtomicOp.h, src/stdpar/plugin-PixelVertexFinding/PixelVertexProducerCUDA.cc, src/stdpar/plugin-PixelVertexFinding/gpuFitVertices.h, src/stdpar/plugin-PixelVertexFinding/gpuSortByPt2.h, src/stdpar/plugin-PixelVertexFinding/gpuSplitVertices.h, src/stdpar/plugin-PixelVertexFinding/gpuVertexFinderImpl.h, src/stdpar/test/VertexFinder_t.h
Port of `plugin-PixelVertexFinding` to `std::par`.
The original CUDA threading model was to process one module per thread block for most kernels. Parallel algorithms don't currently allow to express this model; as single execution of a `std::for_each` lambda will map to one thread so we now have one thread per module. 
There is still an issue when compiling `gpuVertexFinder::loadTracks`, `nvc++` hangs and never finishes
=> `std::par` implementation of `plugin-PixelVertexFinding`

src/stdpar/plugin-PixelVertexFinding/gpuSplitVertices.h
With the new threading model of `nvc++` processing one vertex/thread instead of one vertex/block, we need to allocate arrays for each thread.
=> [stdpar] Updated splitVertices kernel so that each vertex has its own set of arrays

Makefile, src/stdpar/plugin-PixelTriplets/BrokenLine.h, src/stdpar/plugin-PixelTriplets/BrokenLineFitOnGPU.cu, src/stdpar/plugin-PixelTriplets/BrokenLineFitOnGPU.h, src/stdpar/plugin-PixelTriplets/CAConstants.h, src/stdpar/plugin-PixelTriplets/CAHitNtupletCUDA.cc, src/stdpar/plugin-PixelTriplets/CAHitNtupletGeneratorKernels.cu, src/stdpar/plugin-PixelTriplets/CAHitNtupletGeneratorKernelsAlloc.h, src/stdpar/plugin-PixelTriplets/CAHitNtupletGeneratorKernelsImpl.h, src/stdpar/plugin-PixelTriplets/CAHitNtupletGeneratorOnGPU.h, src/stdpar/plugin-PixelTriplets/FitResult.h, src/stdpar/plugin-PixelTriplets/FitUtils.h, src/stdpar/plugin-PixelTriplets/GPUCACell.h, src/stdpar/plugin-PixelTriplets/RiemannFit.h, src/stdpar/plugin-PixelTriplets/RiemannFitOnGPU.cu, src/stdpar/plugin-PixelTriplets/RiemannFitOnGPU.h, src/stdpar/plugin-PixelTriplets/gpuFishbone.h, src/stdpar/plugin-PixelTriplets/gpuPixelDoublets.h, src/stdpar/plugin-PixelVertexFinding/gpuFitVertices.h, src/stdpar/plugin-PixelVertexFinding/gpuSplitVertices.h
Port`plugin-PixelTriplets` to `std::par`. There are still some bugs that need to be fixed when running the application but all the modules have been ported to stdpar and compiles using nvhpc 23.1.
=> [stdpar] Port pixel triplets plugin to `stdpar`

Makefile
Upgrading the oneTBB external to `2021.7.0`.
Compiles, runs and passes validation.
=> Upgrade oneTBB to 2021.7.0

src/openmp/plugin-PixelVertexFinding/gpuClusterTracksByDensity.h, src/openmp/plugin-PixelVertexFinding/gpuFitVertices.h, src/openmp/plugin-PixelVertexFinding/gpuSplitVertices.h, src/openmp/plugin-PixelVertexFinding/gpuVertexFinderImpl.h
Port code in the PixelVertexFinding plugin to use OpenMP offload.
What remains to be done:
* Many of the loops are in individual `target` regions, which makes them separate kernels.  This is likely to lead to large launch overheads in aggregate.  The loop in `gpuSplitVertices` is different - the outer loops is `target teams distribute`, and the inner loops are `parallel for`.   The other kernels may need to be modified to do something similar in order to combine multiple loops in a single kernel invocation.
* Each kernel has the data movement pulled out of individual loops into a `target enter/exit data` region.  These regions should be be expanded to encompass the all the kernels.
* Sorting in `gpuSortByPt2` has not been ported.
The `atomicInc` function, which performs a clipped or …
=> [OpenMP] Initial port of PixelVertexFinding

Makefile
Update oneTBB to v2021.9.0, and check out Alpaka over https.
=> Update oneTBB and Alpaka

Makefile, src/sycl/bin/main.cc, src/sycl/test/AtomicPairCounter_t.cc, src/sycl/test/HistoContainer_t.cc, src/sycl/test/OneHistoContainer_t.cc, src/sycl/test/OneToManyAssoc_t.cc, src/sycl/test/VertexFinder_t.cc, src/sycl/test/gpuClustering_t.cc, src/sycltest/bin/main.cc
Use `ONEAPI_DEVICE_SELECTOR` instead of the legacy `SYCL_DEVICE_FILTER`.
Improve the synchronisation and error handling of the SYCL queues.
Downgrade the error about missing oneAPI to a warning.
=> Update the SYCL device selector and improve the synchronisations 

Makefile, src/sycl/CondFormats/PixelCPEFast.cc, src/sycl/CondFormats/SiPixelFedCablingMapGPUWrapper.cc, src/sycl/CondFormats/SiPixelGainCalibrationForHLTGPU.cc, src/sycl/SYCLDataFormats/SiPixelDigisSYCL.cc, src/sycl/SYCLDataFormats/TrackingRecHit2DSYCL.h, src/sycl/plugin-PixelTriplets/BrokenLineFitOnGPU.cc, src/sycl/plugin-PixelTriplets/CAHitNtupletGeneratorOnGPU.cc, src/sycl/plugin-PixelVertexFinding/gpuVertexFinderImpl.h, src/sycl/plugin-SiPixelClusterizer/SiPixelRawToClusterGPUKernel.cc, src/sycl/plugin-SiPixelRecHits/PixelRecHits.cc
Automatically enable the workarounds for the OpenCL CPU back-end based on the `__SYCL_TARGET_INTEL_X86_64__` macro, instead of by setting the `CPU_DEBUG` macro explicitly.
Add the path to the TBB library to the `LD_LIBRARY_PATH`: the AOT compiler for the CPU target requires the OpenCL CPU runtime. In turn, the OpenCL CPU runtime requires the TBB library.
=> Updates for the SYCL CPU target

Makefile, src/alpaka/AlpakaCore/AllocatorPolicy.h, src/alpakatest/AlpakaCore/AllocatorPolicy.h
Also, let HIP fall back to hipMallocAsync for the alpaka and alpakatest applications.
=> Update to ROCm 5.6.0

src/alpaka/Makefile, src/alpakatest/Makefile, src/cuda/Makefile, src/cudacompat/Makefile, src/cudadev/Makefile, src/cudatest/Makefile, src/cudauvm/Makefile, src/fwtest/Makefile, src/hip/Makefile, src/hiptest/Makefile, src/kokkos/Makefile, src/kokkostest/Makefile, src/openmp/Makefile, src/serial/Makefile, src/stdpar/Makefile, src/sycl/Makefile, src/sycltest/Makefile
On Ubuntu 22.04 using the system compiler (gcc 11.4.0) the calls to `dlopen()` fail because the plugins are not able to find the shared libraries.
For example
```
$ ./cudatest
Found 1 devices
terminate called after throwing an instance of 'std::runtime_error'
what():  unable to load /home/fwyzard/src/pixeltrack-standalone/lib/cudatest/pluginTest1.so because libCUDACore.so: cannot open shared object file: No such file or directory
Aborted (core dumped)
```
And according to `ldd`:
```
$ ldd lib/cudatest/pluginTest1.so
linux-vdso.so.1 (0x00007ffc3977e000)
libFramework.so => not found
libCUDACore.so => not found
libDataFormats.so => not found
libtbb.so.12 => /home/fwyzard/src/pixeltrack-standalone/external/tbb/lib/libtbb.so.12 (0x00007fd0bb44f000)
libcudart.so.12 => …
```
=> Add `-rpath` to the shared libraries

src/alpaka/bin/main.cc
Fail with an explicit message if no back-ends are specified on the command line:
> No back-ends specified, please choose one or more among --serial, --tbb, --cuda, --hip.
=> [alpaka] Require at least one back-end
